#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

@author: shwethakrishnan
"""
import random

def word_frequencies(filename):
    """ uses the text file with the specified filename to create and return
        a dictionary of word frequencies for words in that text file.
        input: filename is a string specifying the name of a text file,
               which we assume is in the same folder as this Python file
    """
    file = open(filename, 'r')
    text = file.read()      # read it all in at once!
    file.close()

    words = text.split()

    d = {}

    for word in words:
        if word not in d:
            d[word] = 1
        else:
            d[word] += 1

    return d

def create_dictionary(filename):
    """create_dictionary(filename) that takes a string representing the 
    name of a text file, and that returns a dictionary of key-value 
    pairs in which: each key is a word encountered in the text file 
    and the corresponding value is a list of words that follow the key word in the text file.
    """
    open_file=open(filename,'r')
    words=open_file.read()
    words=words.split()
    d={}
    current_word='$'
    for next_word in words:
        if current_word not in d:
            d[current_word]=[next_word]
        else:
            d[current_word]+=[next_word]
        if current_word=='$':
            current_word=next_word
        elif next_word[-1]=='.' or next_word[-1]=='!' or next_word[-1]=='?':
            current_word='$'
        elif current_word[-1]=='.' or current_word[-1]=='?' or current_word[-1]=='!':
            current_word=current_word[0:-2]
        else:
            current_word=next_word
    return d

def generate_text(word_dict, num_words):
    """function generate_text(word_dict, num_words) that takes as 
    parameters a dictionary of word transitions (generated by the create_dictionary function) 
    named word_dict and a positive 
    integer named num_words. The function should use word_dict 
    to generate and print num_words words. 
    """
    current_word='$'
    for w in range(num_words):
        next_word = random.choice(word_dict[current_word])
        print(next_word, end=' ')
        
        if next_word[-1]=='.' or next_word[-1]=='!' or next_word[-1]=='?':
            current_word='$'
        else:
            current_word=next_word
    print()